
name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checkout_and_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code from ${{ github.repository }}
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 8
      - name: Install node dependencies
        run: npm ci
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Ruby gems
        run: make install
      - name: Build and serve Jekyll website
        run: make serve &
      - name: Test Jekyll website with Pa11y
        run: make test
